name: 'Garden EKS Deploy Action'
description: 'Configures Garden and AWS credentials for doing Deployments'
inputs:
  ssh_key:  # id of input
    description: 'ssh key'
    required: true
branding:
  icon: 'box'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
